name: 5 Deploy Image to Container Apps V2

on: workflow_dispatch

env:
  AZURE_RG: pi-rg-dev-lab-mpereira
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_REGION: eastus
  ACR_LOGINSERVER: ${{ secrets.ACR_LOGINSERVER }}
  IMAGE_NAME: oabot
  IMAGE_TAG: 3978
  CONTAINER_APP_NAME: mapoabotdemov2
  CONTAINER_APP_ENV:  env-46p6h5mvmhuti

jobs:
  deploy-container-app:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: Create Container App Bot
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az containerapp create -n ${{ env.CONTAINER_APP_NAME }}  -g ${{ env.AZURE_RG }} --environment ${{ env.CONTAINER_APP_ENV }} --yaml "yaml_files/containerapp_config.yml"
